import type { TString, TNumber, TInteger, TBoolean, TNull, TLiteral, TVoid, TUndefined, TUnknown, TAny, TNever, TTemplateLiteral, TSymbol, TFunction, TConstructor, TPromise, TIterator, TAsyncIterator, TSchema } from './schema.js';
export declare function String(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Number(options?: Partial<Omit<TNumber, "'~kind'">>): TNumber;
export declare function Integer(options?: Partial<Omit<TInteger, "'~kind'">>): TInteger;
export declare function Boolean(options?: Partial<Omit<TBoolean, "'~kind'">>): TBoolean;
export declare function Null(options?: Partial<Omit<TNull, "'~kind'">>): TNull;
export declare function Literal<const TValue extends string | number | boolean>(value: TValue, options?: Partial<Omit<TLiteral<TValue>, "'~kind' | 'const'">>): TLiteral<TValue>;
export declare function Void(options?: Partial<Omit<TVoid, "'~kind'">>): TVoid;
export declare function Undefined(options?: Partial<Omit<TUndefined, "'~kind'">>): TUndefined;
export declare function Unknown(options?: Partial<Omit<TUnknown, "'~kind'">>): TUnknown;
export declare function Any(options?: Partial<Omit<TAny, "'~kind'">>): TAny;
export declare function Never(options?: Partial<Omit<TNever, "'~kind'">>): TNever;
export declare function Uuid(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Email(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Uri(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Hostname(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Ip(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Base64(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Hex(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function HexColor(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Date(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function DateTime(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Time(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Duration(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Json(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function CreditCard(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Uint8Array(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function RegExp(options?: Partial<Omit<TString, "'~kind'">>): TString;
export declare function Symbol(options?: Partial<Omit<TSymbol, "'~kind'">>): TSymbol;
export declare function TemplateLiteral(patterns: string[], options?: Partial<Omit<TTemplateLiteral, "'~kind' | 'patterns'">>): TTemplateLiteral;
export declare function Function(parameters?: TFunction['parameters'], returns?: TFunction['returns'], options?: Partial<Omit<TFunction, "'~kind' | 'parameters' | 'returns'">>): TFunction;
export declare function Constructor(parameters?: TConstructor['parameters'], returns?: TConstructor['returns'], options?: Partial<Omit<TConstructor, "'~kind' | 'parameters' | 'returns'">>): TConstructor;
export declare function Promise<T extends TSchema = TSchema>(item: T, options?: Partial<Omit<TPromise<T>, "'~kind' | 'item'">>): TPromise<T>;
export declare function Iterator<T extends TSchema = TSchema>(item: T, options?: Partial<Omit<TIterator<T>, "'~kind' | 'item'">>): TIterator<T>;
export declare function AsyncIterator<T extends TSchema = TSchema>(item: T, options?: Partial<Omit<TAsyncIterator<T>, "'~kind' | 'item'">>): TAsyncIterator<T>;
//# sourceMappingURL=primitives.d.ts.map